// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: job.sql

package database

import (
	"context"
)

const findJobById = `-- name: FindJobById :one
SELECT id, user_id, title, location, description, created_at, updated_at FROM jobs
WHERE id = $1
LIMIT 1
`

func (q *Queries) FindJobById(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, findJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Location,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
