// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	FindJobById(ctx context.Context, id int64) (Job, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
